server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    add_header Content-Security-Policy "
        default-src 'self';
        script-src 'self' 'unsafe-eval'
            https://maps.googleapis.com
            https://maps.gstatic.com
            https://www.gstatic.com                                                                    
            https://www.google.com;                                                                    
        style-src 'self' 'unsafe-inline'                                                               
            https://fonts.googleapis.com;                                                              
            font-src 'self' data:                                                                          
            https://fonts.gstatic.com;  
        img-src 'self' data: blob:
            https://*.googleapis.com
            https://*.gstatic.com;
        connect-src 'self'
            https://airtellecta-back-589274708348.us-central1.run.app
            https://*.googleapis.com
            https://securetoken.googleapis.com
            https://identitytoolkit.googleapis.com
            https://firebaseinstallations.googleapis.com
            https://*.firebaseio.com
            wss://*.firebaseio.com
            https://geodata.ucdavis.edu;

        frame-src 'self'
            https://*.firebaseapp.com
            https://www.google.com;
        
        object-src 'none';
        base-uri 'self';
        form-action 'self';
        frame-ancestors 'none';
        worker-src blob:;
    " always;

    add_header X-Content-Type-Options   "nosniff" always;
    add_header X-Frame-Options          "DENY" always;
    add_header Referrer-Policy          "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy       "camera=(), microphone=(), geolocation=()" always;

 
    location / {
        try_files $uri $uri/ /index.html;
    }
}
